### ISSUE TITLE
Cannot download from Community plug ins or manual

### ISSUE THREAD

**Issue by ArtemisFowl-san** [conneroisu/vim-toggle#1]
Hey, thanks for creating the plug in. I ran into the same issue when using canvas.

Unfortunately, it cannot be downloaded from community plug ins and manual installs also fail for me right now. It says that the main.js is missing from the latest release.

**Comment by ohare93** [comment]
Same here, cannot find the plugin in the Community Plugins list.

**Comment by conneroisu** [comment]
You should be able to install after `npm i`, by running `npm run dev`. Looking for this to be added to the COmmunity Plugins and will update this issue accordingly with the results of that process.

**Comment by roovo** [comment]
Hi @conneroisu - from what I can see, your plugin submission will not be accepted as you don't have all the right stuff in place....  If you have a look at https://marcus.se.net/obsidian-plugin-docs/publishing/submit-your-plugin it lets you know what you need to do.

It looks like you are mostly there; I think all you need to do is to create a release (at the moment you have only tags and no releases) with the tag version matching that in your manifest.json (currently 0.1.4) and which contains the specified files, which in your case would be the `manifest.json` file and the output file from your build process (which should be `main.js`).

There is an automated process you can use (I've not tried it but many plugin authors do use it), which is linked to from the above article too.  I'd probably advise doing it manually first though.

If in doubt, have a look at the contents of releases for a plugin which has been successfully accepted as this may help.

Hope this is useful (the above article certainly is) - I know when I first made my plugin I didn't get this quite right!

**Comment by cocoonkid** [comment]
Yes make it possible ! ;-)

**Comment by hollyhudson** [comment]
I would love to have a toggle for mobile.  When I'm working with my iPad half the time I have a keyboard plugged in (so I'm using vim) and the other half I'm sitting on a couch or something using the stylus, and vim really doesn't work in that situation. Would really like a streamlined way to switch back and forth as needed -- so I'm looking forward to this becoming a community plugin.

**Comment by umamiMike** [comment]
I would love it too!  I frequently find myself wanting this feature.  I manually installed it, but not having to do that would be superb.   Thanks for the work.

**Comment by conneroisu** [comment]
The plugin is officially released. It is doing very well already, but thought I would use this time to close this issue. YAY
