### ISSUE TITLE
Adding key bindings for exiting insert mode and ...

### ISSUE THREAD

**Issue by shayanheidari** [conneroisu/vim-toggle#7]
it would be awesome to have a key binding for exiting the insert mode to normal mode and also view mode to normal mode 

I'll use `jk` for that myself but many may use `jj` key to exit insert mode 

thanks for the awesome plugin 💎

**Comment by conneroisu** [comment]
I think that a command like this could more easily aligned wother plugins that could provide this feature. For instance, it may be best to use something like [commander](https://github.com/phibr0/obsidian-commander) and just providing commands for specifically turning it on or off which I kind of like more than creating a process over the editor listening for additional commands just for vim toggle.
