### ISSUE TITLE
Hooks for toggling

### ISSUE THREAD

**Issue by matthewturk** [conneroisu/vim-toggle#8]
Hi!  I love this plugin.  I was wondering if it might be possible to put hooks in for toggling.  This might be something that could be made generic, but the one hook that I think I would really benefit from would be to auto-toggle to make sure I'm *not* in vim mode when I add a card to a Canvas.

It might be sufficient to be able to do this just when `file-open` is triggered and the new file is a canvas -- have it drop back from vim mode then.  This could be stuck behind a toggle setting.

This may be out of scope for this plugin, but it also seems like the best place for it.  Would you be open to a PR implementing it?

**Comment by conneroisu** [comment]
Honestly, I think i like it! I would prefer it as a setting that one would have opt-in into however I will take a crack at this tomorrow.

**Comment by conneroisu** [comment]
Honestly, I think i like it! I would prefer it as a setting that one would have opt-in into however I will take a crack at this tomorrow.  Thinking about a name like "Automatic Canvas Insert [opt-in]". I also agree that it should easy to do with on open  invoked function.

**Comment by conneroisu** [comment]
Actually, I would happily accept a pr for this feature as I have a small amount of time to work on this feature right now.

**Comment by matthewturk** [comment]
Thank you!  I will give it a go and see what I can come up with.  I appreciate the nudge!
